name: ci

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test-pack:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Knight.Response.sln

      - name: Build
        run: dotnet build Knight.Response.sln -c Release --no-restore

      - name: Test
        run: dotnet test Knight.Response.sln -c Release --no-build --verbosity normal

      - name: Pack (dry run for all packages)
        run: |
          mkdir -p artifacts
          dotnet pack src/Knight.Response/Knight.Response.csproj -c Release -o artifacts --no-build /p:ContinuousIntegrationBuild=true
          dotnet pack src/Knight.Response.Abstractions.Http/Knight.Response.Abstractions.Http.csproj -c Release -o artifacts --no-build /p:ContinuousIntegrationBuild=true
          dotnet pack src/Knight.Response.AspNetCore/Knight.Response.AspNetCore.csproj -c Release -o artifacts --no-build /p:ContinuousIntegrationBuild=true
          dotnet pack src/Knight.Response.Mvc/Knight.Response.Mvc.csproj -c Release -o artifacts --no-build /p:ContinuousIntegrationBuild=true

      - name: Show package contents
        run: |
          ls -lah artifacts
          for pkg in artifacts/*.nupkg; do
            echo "---- $pkg ----"
            unzip -l "$pkg" | sed -n '1,12p'
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/*
          if-no-files-found: error