name: mutation-test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  stryker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore tools & packages
        run: |
          dotnet tool restore
          dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Run mutation tests
        run: dotnet stryker --config-file stryker-config.json

      - name: Upload Stryker report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: stryker-report 
          path: |
            StrykerReports/**/index.html
            StrykerReports/**/stryker-report.json