name: publish

on:
  push:
    tags:
      - 'response-v*'
      - 'aspnetcore-v*'

permissions:
  contents: read

jobs:
  # ============================
  # Knight.Response (response-v*)
  # ============================
  publish-response:
    if: startsWith(github.ref, 'refs/tags/response-v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Knight.Response.sln

      - name: Build
        run: dotnet build Knight.Response.sln -c Release --no-restore

      - name: Test
        run: dotnet test Knight.Response.sln -c Release --no-build --verbosity normal

      - name: Derive version from tag (Knight.Response)
        run: echo "PKG_VERSION=${GITHUB_REF_NAME#response-v}" >> "$GITHUB_ENV"

      # Optional: sanity check
      - name: Check csproj version (optional)
        run: |
          csproj="src/Knight.Response/Knight.Response.csproj"
          declared=$(awk -F'[<>]' '/<Version>/{print $3; exit}' "$csproj" 2>/dev/null || true)
          echo "Declared Version=$declared; Tag Version=$PKG_VERSION"
          if [ -n "$declared" ] && [ "$declared" != "$PKG_VERSION" ]; then
            echo "::warning ::csproj version ($declared) does not match tag ($PKG_VERSION)"
          fi

      - name: Extract release notes from CHANGELOG (Knight.Response)
        shell: bash
        env:
          FILE: src/Knight.Response/CHANGELOG.md
          VER:  ${{ env.PKG_VERSION }}
        run: |
          set -euo pipefail
          if [[ -f "$FILE" ]] && grep -qE "^## \\[\\s*${VER}\\s*\\]" "$FILE"; then
            {
              echo "RELEASE_NOTES<<EOF"
              awk -v ver="$VER" '
                $0 ~ "^## \\[\\s*" ver "\\s*\\]" { p=1; next }
                p && $0 ~ "^## \\["           { p=0 }
                p
              ' "$FILE"
              echo "EOF"
            } >> "$GITHUB_ENV"
          else
            echo "RELEASE_NOTES=See CHANGELOG.md for details." >> "$GITHUB_ENV"
          fi

      - name: Prepare release notes file (Knight.Response)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p artifacts

          # 1) Raw notes -> file
          printf '%s\n' "${RELEASE_NOTES:-}" | tr -d '\r' > artifacts/release-notes.raw

          # 2) Collapse to single line with HTML newlines so NuGet renders line breaks
          if [ -s artifacts/release-notes.raw ]; then
            awk '{printf "%s&#10;", $0}' artifacts/release-notes.raw > artifacts/release-notes.escaped
            sed -i 's/&#10;$//' artifacts/release-notes.escaped
          else
            : > artifacts/release-notes.escaped
          fi

          # 3) Build MSBuild response file
          {
            echo "/p:ContinuousIntegrationBuild=true"
            printf "/p:PackageReleaseNotes="
            cat artifacts/release-notes.escaped
            echo
          } > artifacts/pack.rsp

      - name: Pack (Knight.Response using response file)
        run: |
          set -euo pipefail
          dotnet pack src/Knight.Response/Knight.Response.csproj \
            -c Release -o artifacts --no-build \
            @artifacts/pack.rsp

      - name: Upload package artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: response-packages
          path: artifacts/*.nupkg

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: >
          dotnet nuget push artifacts/*.nupkg
          -k "$NUGET_API_KEY"
          -s https://api.nuget.org/v3/index.json
          --skip-duplicate

  # ======================================
  # Knight.Response.AspNetCore (aspnetcore-v*)
  # ======================================
  publish-aspnetcore:
    if: startsWith(github.ref, 'refs/tags/aspnetcore-v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Knight.Response.sln

      - name: Build
        run: dotnet build Knight.Response.sln -c Release --no-restore

      - name: Test
        run: dotnet test Knight.Response.sln -c Release --no-build --verbosity normal

      - name: Derive version from tag (AspNetCore)
        run: echo "PKG_VERSION=${GITHUB_REF_NAME#aspnetcore-v}" >> "$GITHUB_ENV"

      # Optional: sanity check
      - name: Check csproj version (optional)
        run: |
          csproj="src/Knight.Response.AspNetCore/Knight.Response.AspNetCore.csproj"
          declared=$(awk -F'[<>]' '/<Version>/{print $3; exit}' "$csproj" 2>/dev/null || true)
          echo "Declared Version=$declared; Tag Version=$PKG_VERSION"
          if [ -n "$declared" ] && [ "$declared" != "$PKG_VERSION" ]; then
            echo "::warning ::csproj version ($declared) does not match tag ($PKG_VERSION)"
          fi

      - name: Extract release notes from CHANGELOG (AspNetCore)
        shell: bash
        env:
          FILE: src/Knight.Response.AspNetCore/CHANGELOG.md
          VER:  ${{ env.PKG_VERSION }}
        run: |
          set -euo pipefail
          if [[ -f "$FILE" ]] && grep -qE "^## \\[\\s*${VER}\\s*\\]" "$FILE"; then
            {
              echo "RELEASE_NOTES<<EOF"
              awk -v ver="$VER" '
                $0 ~ "^## \\[\\s*" ver "\\s*\\]" { p=1; next }
                p && $0 ~ "^## \\["           { p=0 }
                p
              ' "$FILE"
              echo "EOF"
            } >> "$GITHUB_ENV"
          else
            echo "RELEASE_NOTES=See CHANGELOG.md for details." >> "$GITHUB_ENV"
          fi

      - name: Prepare release notes file (AspNetCore)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p artifacts

          # 1) Raw notes -> file
          printf '%s\n' "${RELEASE_NOTES:-}" | tr -d '\r' > artifacts/release-notes-asp.raw

          # 2) Collapse to single line with HTML newlines
          if [ -s artifacts/release-notes-asp.raw ]; then
            awk '{printf "%s&#10;", $0}' artifacts/release-notes-asp.raw > artifacts/release-notes-asp.escaped
            sed -i 's/&#10;$//' artifacts/release-notes-asp.escaped
          else
            : > artifacts/release-notes-asp.escaped
          fi

          # 3) Build MSBuild response file
          {
            echo "/p:ContinuousIntegrationBuild=true"
            printf "/p:PackageReleaseNotes="
            cat artifacts/release-notes-asp.escaped
            echo
          } > artifacts/pack-asp.rsp

      - name: Pack (Knight.Response.AspNetCore using response file)
        run: |
          set -euo pipefail
          dotnet pack src/Knight.Response.AspNetCore/Knight.Response.AspNetCore.csproj \
            -c Release -o artifacts --no-build \
            @artifacts/pack-asp.rsp

      - name: Upload package artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aspnetcore-packages
          path: artifacts/*.nupkg

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: >
          dotnet nuget push artifacts/*.nupkg
          -k "$NUGET_API_KEY"
          -s https://api.nuget.org/v3/index.json
          --skip-duplicate